- name: install vsftpd
  yum:
    name: vsftpd
    state: latest

- name: set ftpd_anon_write = on
  command: setsebool ftpd_anon_write on

#- name: start and enable httpd
#  service:
#    name: vsftpd
#    state: started
#    enabled: true

- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: ftp
    permanent: yes
    state: enabled
    immediate: yes

- name: upload vsftpd.conf
  template:
    src: vsftpd.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify: vsftpd restart

- name: Create a directory if it does not exist
  file:
    path: /var/ftp/pub
    state: directory
    mode: '0755'
    owner: ftp

- name: change selinux context
  shell: chcon -t public_content_rw_t /var/ftp/pub
  notify: verify context 
